apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${APP_NAME}'
  labels:
    app: '${APP_NAME}'
    app.kubernetes.io/version: ${TAG}
spec:
  selector:
    matchLabels:
      app: '${APP_NAME}'
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: '${APP_NAME}'
          image: '${IMAGE_URL}'
          ports:
            - containerPort: ${APP_PORT}
          imagePullPolicy: Always
          tty: true
          resources:
              limits:
                memory: '512Mi'
                cpu: '1'
          readinessProbe:
              httpGet:
                path: /
                port: ${APP_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: '${APP_NAME}'
  labels:
    app: '${APP_NAME}'
    app.kubernetes.io/version: ${TAG}
spec:
  ports:
    - port: ${APP_PORT}
      protocol: TCP
  selector:
    app: '${APP_NAME}'
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: '${APP_NAME}'
  labels:
    app: '${APP_NAME}'
    app.kubernetes.io/version: ${TAG}
spec:
  to:
    kind: Service
    name: '${APP_NAME}'
